version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14
      - image: circleci/postgres:9.5-postgis
        environment:
          POSTGRES_USER: anypay_test
          POSTGRES_DB: anypay_test
          POSTGRES_PASSWORD: "letmein"
      - image: rabbitmq:3
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
            #      - run:
            #name: Migrate & Seed Test Database
            #command: npm run db:migrate
            #- run:
            #name: Seed Prices
            #command: npm run db:seed:prices
      - run:
          name: Run Main Tests
          command: npm test
      - run:
          name: Report Code Coverage
          command: |
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            chmod +x codecov
            ./codecov
      - run:
          name: Tag and Release New Version
          command: npx semantic-release

  build_docker:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build -t stevenzeiler/zenyoga.io . 
      - run:
          name: Push to Docker Hub
          command: |
            docker login --username $DOCKER_USER --password $DOCKER_PASSWORD 
            docker push stevenzeiler/zenyoga.io:$CIRCLE_BRANCH

  deploy:
    machine:
      image: ubuntu
    steps:
      - run:
          name: Deploy to Web Servers
          command: echo "no deploy"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - build_docker:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - develop
      - deploy:
          requires:
            - build_docker
          filters:
            branches:
              only:
                - master

